name: "CI environment setup"
description: |
  * set home bazelrc for CI runner
  * set buildbuddy api key

inputs:
  buildbuddy-api-key:
    required: true

runs:
  using: "composite"
  steps:
    - name: setup ci bazelrc
      shell: bash
      run: |
        cp .github/workflows/ci.bazelrc ~/.bazelrc
        echo 'build:remote-cache --remote_header=x-buildbuddy-api-key=${{ inputs.buildbuddy-api-key }}' >> ~/.bazelrc
